# Generated by Django 4.0 on 2021-12-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCompleted',
            fields=[
                ('token', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('certificate_serial', models.CharField(max_length=40, unique=True)),
                ('certificate_subject', models.CharField(max_length=255)),
                ('certificate_principals', models.TextField(blank=True)),
                ('signed_key', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='AuthRequest',
            fields=[
                ('token', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('public_key', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
