# Generated by Django 4.0 on 2021-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0002_alter_authcompleted_certificate_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcompleted',
            name='certificate_serial',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
