# Generated by Django 4.0 on 2021-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0003_alter_authcompleted_certificate_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcompleted',
            name='certificate_serial',
        ),
        migrations.AddField(
            model_name='authcompleted',
            name='serial',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authcompleted',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
