# Generated by Django 4.0 on 2022-02-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0004_remove_authcompleted_certificate_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrequest',
            name='request_type',
            field=models.CharField(default='invalid', max_length=20),
        ),
    ]
