# Generated by Django 4.0.5 on 2022-06-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0003_alter_sshcertificate_extensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshcertificate',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
