# Generated by Django 4.0.5 on 2022-06-20 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ssosh_server.hosts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', ssosh_server.hosts.models.UpperCaseCharField(max_length=255)),
                ('key', models.CharField(default='bc165573-c289-4068-80f1-56f905032fa4', max_length=100)),
                ('grouplink', models.ManyToManyField(related_name='grouplink', to='auth.group')),
                ('userlink', models.ManyToManyField(related_name='userlink', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hostgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LnkHostToHostgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.hostgroup')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
        migrations.CreateModel(
            name='LnkGroupToHostgroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.hostgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LnkGroupToHost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
    ]
