# Generated by Django 4.0.5 on 2022-06-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ssosh_server.hosts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('hostname', ssosh_server.hosts.models.UpperCaseCharField(max_length=255)),
                ('key', models.CharField(default='23b28cb4-b881-4a33-ae69-c296fd2de5ef', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hostgroup',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LnkUserToHostgroup',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.hostgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LnkUserToHost',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LnkHostToHostgroup',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.hostgroup')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
        migrations.CreateModel(
            name='LnkGroupToHostgroup',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.hostgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LnkGroupToHost',
            fields=[
                ('id', ssosh_server.hosts.models.UUIDPrimaryKeyField(max_length=36, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
            ],
        ),
    ]
