# Generated by Django 4.0.5 on 2022-06-20 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(default='b29923e9-25e2-48d2-9b1c-db81044c40c1', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='edbbbee5-a376-4068-b0ce-44c76235d466', max_length=100),
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('somefield', models.CharField(default='cabf668b-f1fc-430f-b71c-d70aeb22196f', max_length=100)),
                ('usrlink', models.ManyToManyField(related_name='testlink', to='hosts.testuser')),
            ],
        ),
    ]
