# Generated by Django 4.0.5 on 2022-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='190762c1-3279-4a2a-a15a-3a3c718b1e9c', max_length=100),
        ),
    ]
