# Generated by Django 4.0.5 on 2022-06-20 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0002_testuser_alter_host_key_testitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='grouplink',
            field=models.ManyToManyField(related_name='grouplinkz', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='34d092e1-9be8-4e3d-9966-43b32d930e5b', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='userlink',
            field=models.ManyToManyField(related_name='userlinkz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='somefield',
            field=models.CharField(default='7249f82b-08d8-4e36-bb15-86f7cbe47b96', max_length=100),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='user',
            field=models.CharField(default='30586776-7369-4c0a-ae48-0c7650fccb1f', max_length=100),
        ),
    ]
