# Generated by Django 4.0.5 on 2022-06-20 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0004_remove_lnkgrouptohostgroup_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='userlink',
            field=models.ManyToManyField(related_name='user_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='d3696cac-5e5b-45a2-b16e-2faaecae5e17', max_length=100),
        ),
    ]
