# Generated by Django 4.0.5 on 2022-06-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hosts', '0006_host_grouplink_host_hostgrouplink_alter_host_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='grouplink',
            field=models.ManyToManyField(related_name='group_link', to='auth.group', verbose_name='Group permissions'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostgrouplink',
            field=models.ManyToManyField(related_name='hostgroup_link', to='hosts.hostgroup', verbose_name='Hostgroup Permissions'),
        ),
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='53919290-2775-44fe-89b2-8a770b3ab7e2', max_length=100),
        ),
    ]
