# Generated by Django 4.0.5 on 2022-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_remove_hostgroup_hostlink_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='18ffa1f2-ed96-4bb3-875a-508f5b1a18ce', max_length=100),
        ),
    ]
