# Generated by Django 4.0.5 on 2022-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='72735311-7732-4189-98db-ecb8c70ec6f5', max_length=100),
        ),
    ]
