# Generated by Django 4.0.5 on 2022-06-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='29700f63-9612-46c5-a094-69b0ecbd3887', max_length=100),
        ),
    ]
