# Generated by Django 4.0.5 on 2022-06-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_hostgroup_grouplink_hostgroup_userlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': 'Host', 'verbose_name_plural': ' Hosts'},
        ),
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='c3f0bcf9-a06b-4e5a-ad0b-52cd28cf1342', max_length=100),
        ),
    ]
