# Generated by Django 4.0.5 on 2022-06-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='fdc74bdb-96b1-498c-aae1-679e2de1d975', max_length=100),
        ),
    ]
