# Generated by Django 4.0.5 on 2022-06-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0018_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='22a7b4d5-1ab4-447a-8a6a-45f8479708cd', max_length=100),
        ),
    ]
