# Generated by Django 4.0.5 on 2022-06-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0019_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='Y68FgMje2ALM3HEq7Go6rsBRINRD153PSW4AYmQUPrk', max_length=100),
        ),
    ]
