# Generated by Django 4.0.5 on 2022-06-22 13:36

from django.db import migrations, models
import ssosh_server.hosts.models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0020_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default=ssosh_server.hosts.models.token_32bit, max_length=100),
        ),
    ]
