# Generated by Django 4.0.5 on 2022-06-21 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuthRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('00f9c3cb-0de6-4ca9-9c9e-baf1ee0ce337'), editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='06sDZgil5JKhxrHT2Lh8ew', max_length=120, unique=True)),
                ('time', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('metadata', models.JSONField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f3600e68-715c-4073-bd3c-e2ea52454cad'), editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('token', models.CharField(default='LR35E4CJWydI4xCK-VbXt3yTH2P280w4wn1VNoB0CfY', max_length=120, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_auth.deviceauthrequest')),
            ],
        ),
    ]
