# Generated by Django 4.0.5 on 2022-06-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device_auth', '0002_remove_deviceaccesstoken_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaccesstoken',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deviceaccesstoken',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c5d39091-d528-4f5a-903b-cbae6b85f5f1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deviceaccesstoken',
            name='token',
            field=models.CharField(default='51_t_7myBtWBGxejf55uu3sJjr2nSZCWkuhzVzmqkRc', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceauthrequest',
            name='code',
            field=models.CharField(default='eMNSME-kfsti8LrwQ3Jpgw', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceauthrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('792f3f2a-a94e-4545-b869-99aa8570c171'), editable=False, primary_key=True, serialize=False),
        ),
    ]
