# Generated by Django 4.0.5 on 2022-06-22 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0003_deviceaccesstoken_user_alter_deviceaccesstoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccesstoken',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0152638f-870a-49ad-a707-f3a4f318168f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deviceaccesstoken',
            name='token',
            field=models.CharField(default='Iedjk5qhJDnABTtSTrEJqQvAbX4kiEQqmBBwj3-hDvE', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceauthrequest',
            name='code',
            field=models.CharField(default='DBrsVZyT0YvTy78aXpPNsg', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='deviceauthrequest',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2efc6ec6-6efd-44bf-8307-8180cb7247f1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
