# Generated by Django 4.0.5 on 2022-06-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0005_deviceauthrequest_scopes_alter_deviceaccesstoken_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceaccesstoken',
            name='scopes',
            field=models.CharField(default='client.login', max_length=255),
        ),
        migrations.AlterField(
            model_name='deviceauthrequest',
            name='scopes',
            field=models.CharField(max_length=255),
        ),
    ]
