# Generated by Django 4.0.5 on 2022-06-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_auth', '0006_deviceaccesstoken_scopes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccesstoken',
            name='scopes',
            field=models.CharField(max_length=255),
        ),
    ]
