# Generated by Django 4.0 on 2021-12-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Host',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('hostname', models.CharField(max_length=255)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='HostGroup',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('groupname', models.CharField(max_length=255)),
        #         ('group_slug', models.CharField(max_length=255, unique=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='UserHostPermission',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='UserHostgroupPermission',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.hostgroup')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='HostGroupAssignment',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.hostgroup')),
        #         ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='GroupHostPermission',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
        #         ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='GroupHostgroupPermission',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
        #         ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.hostgroup')),
        #     ],
        # ),
    ]
