# Generated by Django 4.0 on 2022-02-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_group_permission_host_key_host_user_permission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='group_permission',
        ),
        migrations.RemoveField(
            model_name='host',
            name='user_permission',
        ),
    ]
