# Generated by Django 4.0 on 2022-02-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='key',
            field=models.CharField(default='3e806c03-e0bb-468a-b40d-2150fe09376c', max_length=100),
        ),
    ]
